name: Tests

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  SQLX_OFFLINE: "true"

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@32cb6a5ae30bb0dfc996fa7baf8bf1ed28442fa4 # v3.17.3
      - name: Run tests via devshell
        run: nix develop --accept-flake-config .# --command just test
